export interface ResponseScorm {
    scorms: Scorm[]
}

export interface Scorm {
    "id": number,
    "coursemodule": number,
    "course": number,
    "name": string,
    "intro": string,
    "introformat": number,
    "introfiles": any[],
    "section": number,
    "visible": boolean,
    "groupmode": number,
    "groupingid": number,
    "lang": string,
    "packagesize": number,
    "packageurl": string,
    "version": string,
    "maxgrade": number,
    "grademethod": number,
    "whatgrade": number,
    "maxattempt": number,
    "forcecompleted": boolean,
    "forcenewattempt": number,
    "lastattemptlock": boolean,
    "displayattemptstatus": number,
    "displaycoursestructure": boolean,
    "sha1hash": string,
    "md5hash": string,
    "revision": number,
    "launch": number,
    "skipview": number,
    "hidebrowse": boolean,
    "hidetoc": number,
    "nav": number,
    "navpositionleft": number,
    "navpositiontop": number,
    "auto": boolean,
    "popup": number,
    "width": number,
    "height": number,
    "timeopen": number,
    "timeclose": number,
    "scormtype": string,
    "reference": string,
    "protectpackagedownloads": boolean,
    "updatefreq": number,
    "options": "",
    "completionstatusrequired": any,
    "completionscorerequired": any,
    "completionstatusallscos": number,
    "autocommit": boolean,
    "timemodified": number
}